
disabled_rules:
  - identifier_name
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length

excluded:
  - Dependencies

custom_rules:
  identifier_name:
    min_length: # only min_length
    error: 3 # only error
    excluded: # excluded via string array
      - id
      - URL
      - url
  override_func: # rule identifier
    name: "override in func" # rule name. optional.
    regex: "override (open|public|private|internal|fileprivate)" # matching pattern
    message: "Use like open override or public override instead" # violation message. optional.
    severity: warning # violation severity. optional.
  forbidden_import:
    name: "forbidden import"
    regex: "import (AlamofireImage|Alamofire)"
    message: "Import is forbidden for this project."
    severity: error

line_length: 190
cyclomatic_complexity: 20

attributes:
 always_on_same_line: ["@IBAction", "@IBOutlet"]
 always_on_line_above: ["@IBInspectable", "@UIApplicationMain", "@discardableResult", "@objc"]
